version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: battle-db
    environment:
      POSTGRES_USER: battleuser
      POSTGRES_PASSWORD: battlepassword
      POSTGRES_DB: battleapp
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data: